### ISSUE TITLE
$query->andFilterWhere and $query->query can not be mixed anymore

### ISSUE THREAD

**Issue by nagyt234** [yiisoft/yii2-elasticsearch#171]
I updated my yii2 system from yii2-elasticsearch 2.0 to 2.1 and elasticsearch package from 2.2.1 to 6.2.1. In the old system I could mix` $query->andFilterWhere` and `$query->query` as follows (the search method is in a class derived from yii\elasticsearch\ActiveRecord):
```php
public function search($params)
{
    $query = self::find();

    $dataProvider = new ActiveDataProvider([
        'query' => $query,
    ]);

    $this->load($params);

    $query->andFilterWhere([
        'languageCode' => \Yii::$app->locale->languageCode,
    ]);

    $queryPart = [];
    if (!empty($this->term)) {
        $queryPart['filtered']['query']['multi_match'] = [
        // ES6: $queryPart['bool']['must']['multi_match'] = [
            'query' => $this->term,
            'operator' => 'and',
            'type' => $this->getQueryType($this->term),
            'fields' => [
                'name_*',
                'meta_description_*'
            ]
        ];
    }

    if (!empty($queryPart)) {
        $query->query($queryPart);
    }

    return $dataProvider;
}
```
It worked with ES 2.2.1 without any problem, but now the andFilterWhere overwrites $query->query independently from the sequence. If one of the two parts is removed the other filter works perfectly, only together not. 

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.13.1
| PHP version      | 7.1
| Operating system | Ubuntu 16.04
|ElasticSearch | 6.2.1

**Comment by webspec2012** [comment]
Подтверждаю, проблема существует!

**Comment by mahsa92** [comment]
I have the same problem too.
Is there any other solution to generate this query?

     GET journals/doc/_search {
          "size": 12,
          "query": {
    "constant_score": {
      "filter": {
        "bool": {
          "must": [
            {
              "bool": {
                "must": [
                  {
                    "match_phrase_prefix": {
                      "title": "mytitle"
                    }
                  }
                ]
              }
            },
            {
              "bool": {
                "must": [
                  {
                    "terms": {
                      "categoryId": [
                        "21"
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
      }
     }
    }
    }

**Comment by vov4ik08** [comment]
hello. any news about this problem ?

**Comment by beowulfenator** [comment]
This isn't an outright bug, it's more like a decision we need to make.

I checked the code - this change was introduced by @holycheater along with other numerous fixes for compatibility with ES5. The change also drops filter support (as in true ElasticSearch filters with the `filter` clause in the request) in the `Query` class.

I see no reason to drop filter support (if @holycheater has a comment on that, I'd like to hear it). On the other hand, I see no reason to build queries in such a way that `where()` ultimately creates a filter clause. One approach is not necessarily better than another. The core problem is that ElasticSearch itself is quite different from what the SQL-inspired `QueryBuilder` is designed for.

My personal preference would be to bring back filter support to `Query` because it is a legitimate part of ElasticSearch DSL, but still have `where()` and related methods end up in the `query` clause with a `constant_score` wrapper.

In any event, here's how I would solve your problem. Get rid of `andFilterWhere`. Build all your constraints separately and put them into a `bool` query's `must` clause.

    $must = [];

    if (!empty($this->term)) {
        $must[] = [
            'bool' => [
                'must' => [
                    'multi_match' => [
                        'query' => $this->term,
                        'operator' => 'and',
                        'type' => $this->getQueryType($this->term),
                        'fields' => [
                            'name_*',
                            'meta_description_*'
                        ],
                    ],
                ],
            ],
        ];
    }

    if (!empty(\Yii::$app->locale->languageCode)) {
        $must[] = ['term' => ['languageCode' => \Yii::$app->locale->languageCode]];
    }

    if (!empty($must)) {
        $query->query(['bool' => ['must' => $must]]);
    }

**Comment by samdark** [comment]
I think bringing filters back makes sense.

**Comment by mikehaertl** [comment]
Filters should definitely come back. I just found out that `$query->filter` is completely ignored. So it seems I can not do any filter query at all. Internally filters are used when calling `andWhere()` - but the features here are very limited and usually not what you want.

I agree to what @beowulfenator said. Personally I'd vote to completely refactor the query class and boil it down to the absolute minimum. Elastic != SQL so most features of the query builder are useless in any more complex scenario.

**Comment by mikehaertl** [comment]
After reading more ES docs I have changed my mind: I think filters **should not** come back.

> I see no reason to drop filter support (if @holycheater has a comment on that, I'd like to hear it).

@beowulfenator In my understanding our `Query` class represents a query to the ES' [search API](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-request-body.html). I found there is no top level `filter` parameter in the request body - only `query` (and `postFilter`, which we have). A `filter` can only be used somewhere inside the `query` object. So `Query::$filter` should be removed (it's not used now anyway). 

As you noted ES is different from SQL: the query conditions can be deeply nested in a wild mix depending on the use case. So whatever we do in any `filter()`, `andFilter()` or whatever method - it would only fit one specific use case and miss the expectations in all the other scenarios. A root cause of developer frustration. That's why in my opinion it doesn't make much sense at all. A developer who wants to use ES in his project will have to **learn the DSL** anyway and not rely on some prebuilt logic which may or may not work for his case.

What we *could* have instead: Full support for the query DSL with many classes for all possible query elements (and also aggregations, etc.) to make building dynamic queries a bit easier. Given the AST like structure of a query it would behave different from current `db\Query` methods in that it does not return `$this` for every method call. Something like this:

```php
$bool = $query->bool([
  "minimum_should_match"  => 1,
  "boost" => 1.0,
]);

$must = $bool->must();
$must->match(['name' => 'Foo']);
$must->match(['street' => 'Bar']);

$filter = $bool->filter();
$filter->term(['category' => 123);
```

But IMO that's not maintainable given the limited manpower Yii has. We'd have to support different versions of ES and keep everything up to date with every new release.

**Comment by beowulfenator** [comment]
There's no need to wrap all ES query clauses into classes. `$must->match(['name' => 'Foo'])` is just syntactic sugar for `$must[] =['match' => ['name' => 'Foo']]`;

The only thing that really matters is getting results from queries in yii2-compatible format. And dataproviders. Queries themselves will need to be written in DSL.

**Comment by mikehaertl** [comment]
@beowulfenator Sure, but it would be helpful if you want to build dynamic queries, just like you can do with `andWhere()` in SQL:

```php
if ($this->name) {
    $must->match(['name' => $this->name]);
}
```

But again: Probably too much to maintain.

**Comment by holycheater** [comment]
I dropped filter parameter because it was dropped from elasticsearch since 2.0.
Instead, ES has a filter context which can be present in different parts of the query depending on the query: it may be a part of constant_score/bool query or a part of an aggregation making use `Query::$filter` either ambiguous or some predefined behaviour.

**Comment by beowulfenator** [comment]
I guess this needs to be reflected in the docs.

**Comment by beowulfenator** [comment]
I gave this some thought and the simplest and most straightforward solution is to combine `$query` component with the `$where` component in `QueryBuilder` as a boolean AND (technically as a bool/must query). At least this returns the same results as the previous version of the extension (the scoring is different, but at least the scope is the same).
