### ISSUE TITLE
Support Elasticsearch 8.x

### ISSUE THREAD

**Issue by EvilKarter** [yiisoft/yii2-elasticsearch#325]
Sorry this is more a question than an issue. 

Is Elasticsearch 8.x already supported by this project? 

The current documentation only ever mentions versions 5 to 7.

**Comment by beowulfenator** [comment]
I've accepted a PR recently (#324) that fixes at least one problem with ES8 (the `_update` endpoint instead of `_doc`). ES8 is generally expected to work, I doubt much has changed in its API.

If you find any issues with ES8 while using the latest `master` branch (latest changes haven't been released yet), feel free to report. Thanks!
