### ISSUE TITLE
Disabling the search result limit is not working as it should

### ISSUE THREAD

**Issue by sergeantjonas** [yiisoft/yii2-elasticsearch#87]
I have the following code at the moment that does a working search, everything is working as it should until I wanted to disable the (very) low limit on search results.

```php
$query->query(["query_string" => ["query" => $string]])->limit(null)->search();
````

The docs mention that putting the limit to null or a negative value should disable the limit, but I still only get 10 results returned. Putting the limit above 10 however does work as expected.

I'm using Yii 2.0.8 and yii2-elasticsearch 2.0.4

**Comment by beowulfenator** [comment]
The docs are wrong. Can you please point me to the exact place where it says limit can be disabled so I can fix it?

ES will not let you disable limit. That's because the further you are in your result set, the more resource-intensive it becomes. There is a different API to get all results from a query.

    $query->query(["query_string" => ["query" => $string]])->limit(100);
    foreach ($query->each() as $doc) {
        //do your stuff here
    }

Depending on whether this query can enable scan mode (if ordering is disabled, the highly-efficient scan mode can be enabled), `limit` has different meaning. In normal mode limit is per batch (in this example batch size = 100), in scan mode it is _per shard_ (for a typical index batch size will be now 5*100 = 500).

**Comment by sergeantjonas** [comment]
Seems I was confusing two docs, docs do say that the limit should be specified. Apologies, it's the yii/db/querytrait docs that mention disabling the limit. I guess you can close this.

**Comment by beowulfenator** [comment]
OK.
