### ISSUE TITLE
Error creating records on Amazon Web Services

### ISSUE THREAD

**Issue by ghost** [yiisoft/yii2-elasticsearch#98]
### What steps will reproduce the problem?

Use Amazon Web Services' ElasticSearch service. Attempt to POST a new record to an index.

``` php
/**
 * @property string $name
 */
class User extends \yii\elasticsearch\ActiveRecord
{
    public static function createIndex()
    {
        return static::getDb()->createCommand()->createIndex(static::index(), [
            'mappings' => static::mapping(),
        ]);
    }

    public static function mapping()
    {
        return [
            static::type() => [
                'properties' => [
                    'name' => ['type' => 'string'],
                ],
            ],
        ];
    }

    /**
     * Override to remove 'op_type' => 'create' default in parent's $options.
     *
     * a) should not be needed
     * b) this is the wrong workaround. request should set Content-Type:
     *    application/json but this extension of vendor code is easier
     */
    //public function insert($runValidation = true, $attributes = null, $options = [])
    //{
    //    return parent::insert($runValidation, $attributes, $options);
    //}
}

User::createIndex();

$user = new User(['name' => 'John Doe']);
$user->save();
```
### What's expected?

With the code above as-is, the new record should be created/inserted/saved successfully.
### What do you get instead?

AWS rejects the request with the following 403 Forbidden message:

> When Content-Type:application/x-www-form-urlencoded, URL cannot include query-string parameters (after '?'): '/users/user?op_type=create'
### Additional info

The underlying ElasticSearch product itself allows POST requests with `Content-Type: application/x-www-form-urlencoded` and a JSON request body. While factually invalid (you can't parse a JSON request body using an x-www-form-urlencoded parser), ElasticSearch lets you bastardize the HTTP protocol.

AWS does not permit this. The POST to create a new record is passing a JSON request body, and should be setting `Content-Type: application/json`. The actual method causing this problem is `\yii\elasticsearch\Connection::httpRequest()` which never sets a Content-Type, even though callers are executing this method with `$requestBody` containing a JSON-encoded body.

I have tested that AWS accepts the request if I manually hack the vendor `httpRequest()` method to set the correct Content-Type. Can't fix with one line though, as all JSON requests need to set the Content-Type, while non-JSON requests must remain untouched. The official ElasticSearch product should also not have a problem with this, as all you are doing is setting the proper Content-Type for requests which should require it to begin with.

For now, I am hacking around by overriding the `\yii\elasticsearch\ActiveRecord::insert()` method to remove the `op_type=create` query string, as seen in the commented method in my `User` class above. The proper solution requires making the `httpRequest()` method content-type aware, so as to set `Content-Type: application/json` when appropriate.

| Q | A |
| --- | --- |
| Yii vesion | 2.0.9 |
| yii2-elasticsearch version | 2.0.4 |
| PHP version   5.6.24 |  |
| Operating system | Ubuntu 16.04 LTS |

**Comment by beowulfenator** [comment]
Thank you for the very detailed report. How is the "application/x-www-form-urlencoded" content type selected in the first place? I believe it is implicitly chosen by cURL. Will explicitly setting the content type to "multipart/form-data" for all requests solve the problem?

**Comment by dzentota** [comment]
Faced the same problem, 
if you specify request content-type \yii\elasticsearch\Connection::httpRequest() like

```php
CURLOPT_HTTPHEADER     => ['Expect:', 'Content-type: application/json'],
```
it works. At least you can create/update records and do search, I didn't check the whole bunch of possible scenarios.

Unfortunately I can NOT just override `\yii\elasticsearch\Connection` in my app because `resetCurlHandle()` is a private method as well as $_curl is a private property, so I had to copy paste the whole file for now.

**Comment by reol-nbessette** [comment]
Right. `Content-Type: application/json` is the requirment. `multipart/form-data` will not help, you're still mismatching the header with the request body.

**Comment by beowulfenator** [comment]
Any thoughts on how this can be solved? We cannot simply pass `Content-type: application/json` everywhere, because there are cases when request body is actually a non-json string (e.g. `analyze`).

The only way to know if a string is valid json is to actually try and decode it, which is a performance problem. We could extend `get`, `head`, `post`, `put`, `delete` methods by adding content type as another parameter, but this breaks compatibility.

Do you have any other ideas?

**Comment by dzentota** [comment]
add possibility to pass list of headers to httpRequest():

```php
protected function httpRequest($method, $url, $requestBody = null, $raw = false, $httpHeaders = ['Expect:', 'Content-type: application/json'])
```
extend `get`, `head`, `post`, `put`, `delete` in the same way. 

Of course default value for $httpHeaders can be specified class constant or property
In such case the issue will be fixed in new version and compatible with old implementations

**Comment by beowulfenator** [comment]
@dzentota, it's not entirely compatible, unfortunately. If there is 3rd-party code that extends `httpRequest`, by adding the fifth parameter, it will be broken. However unlikely, technically that breaks BC and we shouldn't do that.

**Comment by dzentota** [comment]
- You can also add hacks to httpRequest() 

1. Check if you've got a valid JSON and add appropriate header if needed:

 ```php
 json_decode($string);
 (json_last_error() == JSON_ERROR_NONE);
```
2. Add appropriate header based on stack trace (even worse than previous variant)

- Add new method e.g. httpRequestJSON() and call it instead of httpRequest() when needed 
- Add new property to Connection and add appropriate headers in httpRequest based on this (in this and previous variant you need additional code which will detect which method to call based on target endpoint)

**Comment by beowulfenator** [comment]
Option 1 is a massive performance hit, especially if body is a large json object with many levels of nesting. We just can't do that. Adding `httpRequestJSON` is not a very good solution either, `httpRequest` is rarely if ever called directly.

Adding a property to Connection looks tempting. It's an ugly solution, but looks like it's best of what we have right now.

Let me think about this for a while.

**Comment by dzentota** [comment]
Also, just FYI, how it was done in ElasticSearch it self:
https://github.com/elastic/elasticsearch/blob/f6aec3fdb53d7e3d7693393c25d5c3012efecb07/core/src/main/java/org/elasticsearch/common/settings/loader/SettingsLoaderFactory.java#L59-L80

**Comment by dzentota** [comment]
And another hint how to detect if you should use "application/json" header:
if URL include query-string parameters (after '?'), like `/users/user?op_type=create`, otherwise query will fail due to error 403: 
When Content-Type:application/x-www-form-urlencoded, URL cannot include query-string parameters (after '?')

**Comment by beowulfenator** [comment]
Is there any other content type that allows query string parameters, yet doesn't explicitly state that it's json?

**Comment by dzentota** [comment]
I don't know such content type. But why can not we just use 'application/json' everywhere (analyze supports json)? 
```
curl -XGET 'localhost:9200/_analyze' -d '
{
  "analyzer" : "standard",
  "text" : "this is a test"
}'
```

**Comment by beowulfenator** [comment]
Fixed with https://github.com/yiisoft/yii2-elasticsearch/commit/944f2d9233a7ee2cc724b340d064685c9484fb74
